"""Physical layout — positions and routes.

Edit positions in KiCad GUI, then run:
    python -m circuit_toolkit.builders.extract_layout usbc-3v3.kicad_pcb layout.py

Routing/zones live below the auto-generated block; they're hand-edited.
"""

# === auto-generated by circuit_toolkit.builders.extract_layout ===
positions = {
    "J1": (5.5, 15, 270),
    "J2": (42, 15, 0),
    "U1": (22, 15, 270),
    "D1": (37, 15, 180),
    "R1": (9, 8.5, 0),
    "R2": (9, 21.5, 0),
    "R3": (33.5, 15, 0),
    "C1": (13, 10.5, 0),
    "C2": (13, 19.5, 0),
    "C3": (30, 10.5, 0),
    "C4": (30, 19.5, 0),
    "H1": (2, 2, 0),
    "H2": (46, 2, 0),
    "H3": (2, 28, 0),
    "H4": (46, 28, 0),
}
# === end auto-generated ===


# Reference-text overrides (silkscreen fixups for tight areas)
ref_text_overrides = {
    "R2": (9.0, 22.8),  # move below to clear J1 SH pad
}

# F.Cu zone connection overrides — for J1 pads totally surrounded by non-GND
pad_zone_full = [
    ("J1", "B7"),
    ("J1", "A8"),
]

# Tracks: (net_name, x1, y1, x2, y2, width_mm, layer)
tracks = [
    # ── VBUS ──
    # 0.3mm stubs from dense J1 pads → vertical VBUS bus at x=11.8
    ("VBUS", 9.545, 12.55, 11.8, 12.55, 0.3, "F.Cu"),
    ("VBUS", 9.545, 17.45, 11.8, 17.45, 0.3, "F.Cu"),
    # Vertical bus (linking both VBUS y-levels)
    ("VBUS", 11.8, 10.5, 11.8, 19.5, 0.5, "F.Cu"),
    # Drops from bus to caps
    ("VBUS", 11.8, 10.5, 12.05, 10.5, 0.3, "F.Cu"),   # → C1 pad1
    ("VBUS", 11.8, 19.5, 12.52, 19.5, 0.3, "F.Cu"),   # → C2 pad1
    # Horizontal bus → U1 pin 3 (VIN)
    ("VBUS", 11.8, 11.85, 19.7, 11.85, 0.8, "F.Cu"),

    # ── +3V3 ──
    # U1 pin2 small (22, 11.85) → up to y=8.5 → horizontal east
    ("+3V3", 22.0, 11.85, 22.0, 8.5, 0.5, "F.Cu"),
    ("+3V3", 22.0, 8.5, 42.0, 8.5, 0.5, "F.Cu"),     # main bus
    # Drops from bus
    ("+3V3", 29.05, 8.5, 29.05, 10.5, 0.3, "F.Cu"),  # → C3 pad1
    ("+3V3", 33.0, 8.5, 33.0, 15.0, 0.5, "F.Cu"),    # spine to R3
    ("+3V3", 32.99, 15.0, 33.0, 15.0, 0.3, "F.Cu"),  # R3 pad1 stub
    ("+3V3", 42.0, 8.5, 42.0, 15.0, 0.5, "F.Cu"),    # → J2 pad1
    # U1 tab (22, 18.15) → east → vertical to join bus
    ("+3V3", 22.0, 18.15, 29.0, 18.15, 0.5, "F.Cu"),
    ("+3V3", 29.0, 8.5, 29.0, 19.5, 0.5, "F.Cu"),    # x=29 spine
    ("+3V3", 29.0, 19.5, 29.52, 19.5, 0.3, "F.Cu"),  # → C4 pad1

    # ── N_D1: R3 pad2 → D1 anode ──
    ("N_D1", 34.01, 15.0, 36.062, 15.0, 0.3, "F.Cu"),

    # ── CC1: J1 A5 → R1 pad1 ──
    # Right-side escape past pad edge (right edge at x=10.27, via at x=10.87)
    ("CC1", 9.545, 13.75, 10.87, 13.75, 0.3, "F.Cu"),
    ("CC1", 10.87, 13.75, 7.0, 13.75, 0.3, "B.Cu"),
    ("CC1", 7.0, 13.75, 7.0, 8.5, 0.3, "B.Cu"),
    ("CC1", 7.0, 8.5, 8.49, 8.5, 0.3, "F.Cu"),

    # ── CC2: J1 B5 → R2 pad1 ──
    ("CC2", 9.545, 16.75, 10.87, 16.75, 0.3, "F.Cu"),
    ("CC2", 10.87, 16.75, 10.87, 16.0, 0.3, "F.Cu"),
    ("CC2", 10.87, 16.0, 7.0, 16.0, 0.3, "B.Cu"),
    ("CC2", 7.0, 16.0, 7.0, 21.5, 0.3, "B.Cu"),
    ("CC2", 7.0, 21.5, 8.49, 21.5, 0.3, "F.Cu"),

    # ── GND bridges: isolated J1 pads the zone can't reach ──
    ("GND", 9.545, 13.25, 7.5, 13.25, 0.25, "F.Cu"),  # B8
    ("GND", 9.545, 14.25, 7.5, 14.25, 0.25, "F.Cu"),  # B7
    ("GND", 9.545, 16.25, 7.5, 16.25, 0.25, "F.Cu"),  # A8
    # SH PTH shield pins → adjacent SMD GND pads (L-routes)
    ("GND", 8.63, 10.68, 9.545, 10.68, 0.25, "F.Cu"),
    ("GND", 9.545, 10.68, 9.545, 11.75, 0.25, "F.Cu"),  # → B12/A1 zone
    ("GND", 8.63, 19.32, 9.545, 19.32, 0.25, "F.Cu"),
    ("GND", 9.545, 19.32, 9.545, 18.25, 0.25, "F.Cu"),  # → A12 zone
]

# Vias: (net_name, x, y, drill_mm, size_mm)
vias = [
    ("CC1", 10.87, 13.75, 0.4, 0.8),
    ("CC1", 7.0, 8.5, 0.4, 0.8),
    ("CC2", 10.87, 16.0, 0.4, 0.8),
    ("CC2", 7.0, 21.5, 0.4, 0.8),
]

# Zones (copper pours)
zones = [
    {
        "net": "GND",
        "layer": "F.Cu",
        "polygon": [(1, 1), (47, 1), (47, 29), (1, 29)],
        "min_thickness": 0.25,
        "pad_connection": "thermal",
    },
]

# Board outline
outline = {"shape": "rect", "x": 0.0, "y": 0.0, "w": 48.0, "h": 30.0}
