"""Physical layout — positions and routes.

Edit positions in KiCad GUI, then run:
    python -m circuit_toolkit.builders.extract_layout usbc-3v3.kicad_pcb layout.py

Routing/zones live below the auto-generated block; they're hand-edited.

Variant support: every track that lands on the regulator's output net
references ``output_net`` (default "+3V3"). Pass a different value to
get_layout() to build the same physical board with a different LDO drop —
the AMS1117-3.3 / -5.0 / -1.8 / -2.5 are all SOT-223, same footprint, same
pad layout, so positions and routes are reusable verbatim.
"""

# === auto-generated by circuit_toolkit.builders.extract_layout ===
positions = {
    "J1": (5.5, 15, 270),
    "J2": (42, 15, 0),
    "U1": (22, 15, 270),
    "D1": (37, 15, 180),
    "R1": (9, 8.5, 0),
    "R2": (9, 21.5, 0),
    "R3": (33.5, 15, 0),
    "C1": (13, 10.5, 0),
    "C2": (13, 19.5, 0),
    "C3": (30, 10.5, 0),
    "C4": (30, 19.5, 0),
    "H1": (2, 2, 0),
    "H2": (46, 2, 0),
    "H3": (2, 28, 0),
    "H4": (46, 28, 0),
}
# === end auto-generated ===


# Reference-text overrides (silkscreen fixups for tight areas)
ref_text_overrides = {
    "R2": (9.0, 22.8),  # move below to clear J1 SH pad
}

# F.Cu zone connection overrides — for J1 pads totally surrounded by non-GND
pad_zone_full = [
    ("J1", "B7"),
    ("J1", "A8"),
]

# Vias: (net_name, x, y, drill_mm, size_mm)
vias = [
    ("CC1", 10.87, 13.75, 0.4, 0.8),
    ("CC1", 7.0, 8.5, 0.4, 0.8),
    ("CC2", 10.87, 16.0, 0.4, 0.8),
    ("CC2", 7.0, 21.5, 0.4, 0.8),
]

# Zones (copper pours)
zones = [
    {
        "net": "GND",
        "layer": "F.Cu",
        "polygon": [(1, 1), (47, 1), (47, 29), (1, 29)],
        "min_thickness": 0.25,
        "pad_connection": "thermal",
    },
]

# Board outline
outline = {"shape": "rect", "x": 0.0, "y": 0.0, "w": 48.0, "h": 30.0}


def _tracks(output_net: str) -> list:
    """All track segments — references `output_net` for the regulator output."""
    return [
        # ── VBUS ──
        ("VBUS", 9.545, 12.55, 11.8, 12.55, 0.3, "F.Cu"),
        ("VBUS", 9.545, 17.45, 11.8, 17.45, 0.3, "F.Cu"),
        ("VBUS", 11.8, 10.5, 11.8, 19.5, 0.5, "F.Cu"),
        ("VBUS", 11.8, 10.5, 12.05, 10.5, 0.3, "F.Cu"),
        ("VBUS", 11.8, 19.5, 12.52, 19.5, 0.3, "F.Cu"),
        ("VBUS", 11.8, 11.85, 19.7, 11.85, 0.8, "F.Cu"),

        # ── output rail (was "+3V3") ──
        (output_net, 22.0, 11.85, 22.0, 8.5, 0.5, "F.Cu"),
        (output_net, 22.0, 8.5, 42.0, 8.5, 0.5, "F.Cu"),
        (output_net, 29.05, 8.5, 29.05, 10.5, 0.3, "F.Cu"),
        (output_net, 33.0, 8.5, 33.0, 15.0, 0.5, "F.Cu"),
        (output_net, 32.99, 15.0, 33.0, 15.0, 0.3, "F.Cu"),
        (output_net, 42.0, 8.5, 42.0, 15.0, 0.5, "F.Cu"),
        (output_net, 22.0, 18.15, 29.0, 18.15, 0.5, "F.Cu"),
        (output_net, 29.0, 8.5, 29.0, 19.5, 0.5, "F.Cu"),
        (output_net, 29.0, 19.5, 29.52, 19.5, 0.3, "F.Cu"),

        # ── N_D1: R3 pad2 → D1 anode ──
        ("N_D1", 34.01, 15.0, 36.062, 15.0, 0.3, "F.Cu"),

        # ── CC1: J1 A5 → R1 pad1 ──
        ("CC1", 9.545, 13.75, 10.87, 13.75, 0.3, "F.Cu"),
        ("CC1", 10.87, 13.75, 7.0, 13.75, 0.3, "B.Cu"),
        ("CC1", 7.0, 13.75, 7.0, 8.5, 0.3, "B.Cu"),
        ("CC1", 7.0, 8.5, 8.49, 8.5, 0.3, "F.Cu"),

        # ── CC2: J1 B5 → R2 pad1 ──
        ("CC2", 9.545, 16.75, 10.87, 16.75, 0.3, "F.Cu"),
        ("CC2", 10.87, 16.75, 10.87, 16.0, 0.3, "F.Cu"),
        ("CC2", 10.87, 16.0, 7.0, 16.0, 0.3, "B.Cu"),
        ("CC2", 7.0, 16.0, 7.0, 21.5, 0.3, "B.Cu"),
        ("CC2", 7.0, 21.5, 8.49, 21.5, 0.3, "F.Cu"),

        # ── GND bridges: isolated J1 pads the zone can't reach ──
        ("GND", 9.545, 13.25, 7.5, 13.25, 0.25, "F.Cu"),  # B8
        ("GND", 9.545, 14.25, 7.5, 14.25, 0.25, "F.Cu"),  # B7
        ("GND", 9.545, 16.25, 7.5, 16.25, 0.25, "F.Cu"),  # A8
        ("GND", 8.63, 10.68, 9.545, 10.68, 0.25, "F.Cu"),
        ("GND", 9.545, 10.68, 9.545, 11.75, 0.25, "F.Cu"),
        ("GND", 8.63, 19.32, 9.545, 19.32, 0.25, "F.Cu"),
        ("GND", 9.545, 19.32, 9.545, 18.25, 0.25, "F.Cu"),
    ]


# Module-level `tracks` for back-compat with build.py callers that import
# the names directly. Default is the canonical 3.3V variant.
tracks = _tracks("+3V3")


def get_layout(output_net: str = "+3V3") -> dict:
    """Return all layout artefacts with the regulator output net rewired.

    Used by variant builds. The default value "+3V3" reproduces the
    canonical layout exactly, so existing build.py callers using the
    module-level ``tracks`` list keep working without changes.
    """
    return {
        "positions": positions,
        "tracks": _tracks(output_net),
        "vias": vias,
        "zones": zones,
        "outline": outline,
        "ref_text_overrides": ref_text_overrides,
        "pad_zone_full": pad_zone_full,
    }
